### ISSUE TITLE
Ticket

### ISSUE THREAD

**Issue by aishaqureshi0312** [aishaqureshi0312/eminent-media#1]
5.border radius of nav menu should be 30px .==>corner radius of drop down (header bar/nav bar) should be 30px .
6.In services section decrease height of all cards and decrease size of all cards and line spacing.==>(home page>services) (height of divs named as stategy,creative etc should be 573px.(also add property of on hover (change color and text check jacksonspalding.com for UX).
7.Increase height of "PHOTOGRAPHY" div also add images in this div as per according to design.
8.In "PHOTOGRAPHY" div text is attached with div border please add section pading at the starting of text in photography section as in above divs.

**Comment by usmankhalid2591** [comment]
Okay, I will get to it.

**Comment by usmankhalid2591** [comment]
Fixed.
