### ISSUE TITLE
Tickets..

### ISSUE THREAD

**Issue by aishaqureshi0312** [aishaqureshi0312/eminent-media#2]
1.Increase the size of "SERVICES,CLIENT WORK and THE EMINENT LIST " to 517px.
2.Add on hover change text and color attribute to  all divs in services section.
3.Apply on hover zoom image property to all images on page.
4.Add " BLOG icon" with text in header.
5.Text in "About " drop down should be Aligned according to "About " text.

**Comment by usmankhalid2591** [comment]
Resolved.
